name: claryft_components
description: "custom components for Claryft"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  loading_animation_widget: ^1.3.0
  shimmer: ^3.0.0
  dropdown_search: ^6.0.2
  build_runner: ^2.5.4
  iconsax: ^0.0.8
  intl: any
  logger: ^2.6.0
  pluto_grid: ^8.0.0
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  hugeicons: ^0.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.3.0

flutter:
  generate: true
  uses-material-design: true

flutter_gen:
  output: lib/gen_assets/
  line_length: 80

  integrations:
    flutter_svg: true
    rive: true
    lottie: true
